jobs:
  path-trigger:
    working_directory: /app
    docker:
      - image: lakruzz/play:latest
        environment:
          CIRCLE_PLAY_PATH_REGEXP: .github/labels.yml
    steps:
      - checkout
      - run:
          name: Check the changeset for a match in $CIRCLE_PLAY_PATH_REGEXP
          command: |
            if [[ \
              $(git diff-tree  --no-commit-id --name-only -r `git rev-parse --short HEAD` \
              | grep -e "$CIRCLE_PLAY_PATH_REGEXP") ]];\
            then \
              echo "Yeeah! We have work to do, run your script here"; \
            else \
              echo "Not my call\!";\
            fi;

workflows:
  version: 2
  Proflow:
    jobs:
      - path-trigger:
          filters:
            branches:
              only: /^master$/
