
version: 2
jobs:

  path-trigger:
    working_directory: /app
    docker:
      - image: lakruzz/play:latest # https://github.com/lakruzz/play
        # For this particular job, the container could be any linux based container
        environment:
          PLAY_PATH_REGEXP: somedir/test1.txt\|somedir/.* #the regexp to match, remember to escape chars that should to be literal (most useful is the "or" pipe: | it should be \|)
    steps:
      - checkout
      - run: # You can remove this step - it's purpose is simply to reveal some info about the state of the environment on Circle CI - can be handy, when unexpected things happen!
          name: Some Useful Debug Info
          command: |
            echo "--------- Git version:"
            git --version

            echo
            echo "--------- Listing all CIRCLE... environment variables:"
            env | sort | grep "CIRCLE"

            echo
            echo "--------- Current directory is:"
            pwd

            echo
            echo "--------- Listing all files in current directory:"
            ls -a

            echo
            echo "--------- SHA1 of HEAD and \$CIRCLE_SHA1 (they should be the same):"
            echo HEAD:          `git rev-parse HEAD`
            echo \$CIRCLE_SHA1: `printenv CIRCLE_SHA1`

            echo
            echo "--------- Listing change set (names only) of \$CIRCLE_SHA1:"
            git diff-tree  --no-commit-id --name-only -r $CIRCLE_SHA1

      - run:
          name: Run if we should
          command: |
            export PLAY_RUN=$(git diff-tree  --no-commit-id --name-only -r $CIRCLE_SHA1 | grep -e "$PLAY_PATH_REGEXP")
            '[[ -z "$PLAY_RUN" ]] && echo "The RegExp didn't match the Change set - nothing to do!" || echo "Yeeah! We have work to do, run your script here!"

workflows:
  version: 2
  Proflow:
    jobs:
      - path-trigger:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
