
version: 2
jobs:

  prep-repo:
    working_directory: /app
    # The primary container is an instance of the first list image listed.
    # Your commands in context of this container.
    docker:
      - image: lakruzz/play:latest
        environment:
          PLAY_USER_NAME:    Circle CI by @Lakruzz
          PLAY_USER_EMAIL:   circleci@lakruzz.com
    steps:
      - checkout
      - run:
          name: Describe the Environment
          command: |
            git --version
            env | sort | grep "CIRCLE"
            pwd
            ls -a
            git rev-parse --short HEAD
      - run:
          name: Introduce the user to the git repo, to prepare for delivery
          command: play --manuscript .circleci/play-proflow-cci-gh.yml --part git_set_user
      - run:
          name: If we're o na ready branch then Rebase, Swap to target branch and then integrate
          command: 'printenv CIRCLECI_BRANCH | grep -e "ready\/*" && play --manuscript .circleci/play-proflow-cci-gh.yml --part integrate || echo Not a ready-branch'
      - save_cache:
          key: the-repo-{{.Revision}}
          paths:
            - .

  jekyll-build:
    working_directory: /app
    docker:
      - image: lakruzz/jekyll-plus:1.0.1
    steps:
      - restore_cache:
          keys:
            - the-repo-{{ .Revision }}
      - run:
          name: Jekyll
          command: jekyll build
      - run:
          name: Log the version
          command: cp version.txt _site/version.txt
      - save_cache:
          key: the-built-repo-{{ .Revision }}
          paths:
            - _site
            - .circleci

  html-proofer:
    working_directory: /app
    docker:
      - image: 18fgsa/html-proofer
    steps:
      - restore_cache:
          keys:
            - the-built-repo-{{ .Revision }}
      - run:
          name: Htmlproofer
          command: htmlproofer --disable-external --allow-hash-href --checks-to-ignore ImageCheck --check-favicon _site

  test2:
    working_directory: /app
    docker:
      - image: 18fgsa/html-proofer
    steps:
      - restore_cache:
          keys:
            - the-built-repo-{{ .Revision }}
      - run:
          name: Htmlproofer
          command: htmlproofer --disable-external --allow-hash-href --checks-to-ignore ImageCheck --check-favicon _site

  test3:
    working_directory: /app
    docker:
      - image: 18fgsa/html-proofer
    steps:
      - restore_cache:
          keys:
            - the-built-repo-{{ .Revision }}
      - run:
          name: Htmlproofer
          command: htmlproofer --disable-external --allow-hash-href --checks-to-ignore ImageCheck --check-favicon _site

  deliver:
    working_directory: /app
    docker:
      - image: lakruzz/play:latest
    steps:
      - restore_cache:
          keys:
            - the-repo-{{ .Revision }}
      - run:
          name: Deliver
          command: play --manuscript .circleci/play-proflow-cci-gh.yml --part deliver

  stage-deploy:
    working_directory: /app/_site
    docker:
      - image: lakruzz/play:latest
        environment:
          PLAY_TARGET_GH_REPO:   lakruzz/stage-circle-lab
          PLAY_USER_NAME:        Circle CI by @Lakruzz
          PLAY_USER_EMAIL:       circleci@lakruzz.com
    steps:
      - restore_cache:
          keys:
            - the-built-repo-{{ .Revision }}
      - run:
          name: Use CNAME.stage if it exist
          command: '[[ -e CNAME.stage ]] && cp -f CNAME.stage CNAME || echo No CNAME.stage file found'
      - run:
          name: Deploy to GitHub Pages
          command: play --manuscript ../.circleci/play-proflow-cci-gh.yml --part ghpages_deploy

  prod-deploy:
    working_directory: /app/_site
    docker:
      - image: lakruzz/play:latest
        environment:
          PLAY_TARGET_GH_REPO:   lakruzz/stage-circle-lab
          PLAY_USER_NAME:        Circle CI by @Lakruzz
          PLAY_USER_EMAIL:       circleci@lakruzz.com
    steps:
      - restore_cache:
          keys:
            - the-built-repo-{{ .Revision }}
      - run:
          name: Deploy to GitHub Pages
          command: play --manuscript ../.circleci/play-proflow-cci-gh.yml --part ghpages_deploy

workflows:
  version: 2
  Proflow:
    jobs:
      - prep-repo
      - jekyll-build:
          requires: # Create the thing to deploy
            - prep-repo
      - html-proofer: # Verify that the thing to deploy is good
          requires:
            - prep-repo
            - jekyll-build
      - test2: # Run more tests in parallel
          requires:
            - prep-repo
            - jekyll-build
      - test3: # Run more tests in parallel
          requires:
            - prep-repo
            - jekyll-build
      - deliver: # Push the target branch to remote - only when all is good and only on ready branches
          requires:
            - prep-repo
            - jekyll-build
            - html-proofer
            - test2
            - test3
          filters:
            branches:
              only:
                - /ready\/.*/
      - stage-deploy:
          requires:
            - prep-repo
            - jekyll-build
            - html-proofer
            - test2
            - test3
          filters:
            branches:
              only:
                - /master/
      - prod-deploy:
          requires:
            - prep-repo
            - jekyll-build
            - html-proofer
            - test2
            - test3
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/ # Semantic version number (semver.org), followed by optional .(dot)+string https://regex101.com/r/0h0zLr/1
