
version: 2
jobs:

  path-trigger:
    working_directory: /app
    docker:
      - image: lakruzz/play:latest # https://github.com/lakruzz/play
        # For this particular job, the container could be any linux based container
        environment:
          PLAY_PATH_REGEXP: somedir/test1.txt\|someotherdir/.* #the regexp to match
            # The is passed onto grep (in shell context) so emember to escape chars
            # that should to be literal (most useful is the "or" pipe: | it should be \|)
    steps:
      - checkout
      - run: # Only prints debug info - you can delete this step
          name: CIRCLE environment variables
          command: env | sort | grep "CIRCLE"
      - run: # Only prints debug info - you can delete this step
          name: Change set of \$CIRCLE_SHA1
            git diff-tree  --no-commit-id --name-only -r $CIRCLE_SHA1

       # 1st line stores the output of the grep in a variable. it looks for a
       # match of our regexp in the names-only changeset of the current commit.
       # this approach allows us to run grep - and fail (no match), without
       # actually failing the Circle CI step and die from a no-match.
       # 2nd line exploits -z test (-z is true when the variable is NOT defined) to
       # have the logical AND come before the logical OR this construc depends on The
       # command in the the logival AND never fails - that's why a simple echo is more
       # than enough, so never run scripts at this position, if it fails it wil
       # trigger the logical OR too (Ooh, snap! Auuch!)
      - run:
          name: Run if we should
          command: |
            export PLAY_RUN=$(git diff-tree  --no-commit-id --name-only -r $CIRCLE_SHA1 \
              | grep -e "$PLAY_PATH_REGEXP")
            [[ -z "$PLAY_RUN" ]] \
              && echo "Not my call!" \
              || echo "Yeeah! We have work to do, run your script here!"

workflows:
  version: 2
  Proflow:
    jobs:
      - path-trigger:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
