
version: 2
jobs:

  integrate:
    working_directory: /app
    # The primary container is an instance of the first list image listed.
    # Your commands in context of this container.
    docker:
      - image: lakruzz/play:latest
        environment:
          PLAY_USER_NAME: Circle CI by @Lakruzz
          PLAY_USER_EMAIL: circleci@lakruzz.com
    steps:
      - checkout
      - run:
          name: Describe the Environment
          command: |
            git --version
            env | sort | grep "CIRCLE"
            pwd
            ls -a
            git rev-parse --short HEAD
      - run:
          name: Prep the git repo for delivery
          command: play --manuscript .circleci/phlow.yml --part git_prep
      - run:
          name: Swap to target branch and integrate
          command: play --manuscript .circleci/phlow.yml --part integrate
      - save_cache:
          key: the-repo-{{.Revision}}
          paths:
            - .

  build:
    working_directory: /app
    docker:
      - image: lakruzz/jekyll-plus:1.0.1
    steps:
      - restore_cache:
          keys:
            - the-repo-{{ .Revision }}
      - run:
          name: Where am I
          command: |
            pwd
            ls -a
            git rev-parse --short HEAD
      - run:
          name: Jekyll
          command: jekyll build
      - save_cache:
          key: the-deploy-{{ .Revision }}
          paths:
            - _site

  test:
    working_directory: /app
    docker:
      - image: 18fgsa/html-proofer
    steps:
      - restore_cache:
          keys:
            - the-deploy-{{ .Revision }}
      - run:
          name: Htmlproofer
          command: htmlproofer --disable-external --allow-hash-href --checks-to-ignore ImageCheck --check-favicon _site

  deliver:
    working_directory: /app
    docker:
      - image: lakruzz/play:latest
        environment:
          PHLOW_GHTOKEN: ${$PHLOW_GHTOKEN:=$GHTOKEN}
    steps:
      - restore_cache:
          keys:
            - the-repo-{{ .Revision }}
      - run:
          name: Where am I?
          command: |
            pwd
            ls -a
            git rev-parse --short HEAD
      - run:
          name: Deliver
          command: play --manuscript .circleci/phlow.yml --part deliver

workflows:
  version: 2
  Phlow:
    jobs:
      - integrate:
          filters:
            branches:
              only:
                - /ready\/.*/
      - build:
          requires:
            - integrate
      - test:
          requires:
            - build
      - deliver:
          requires:
            - test
